/**************************************************************************************************************
 *
 * MODULE: lm35_sensor
 *
 * FILE NAME: main.c
 *
 * Description: test the lm35_sensor with the ADC driver
 *
 * Created on: October 7, 2022
 *
 * Author: Saeed Elsayed
 *
 **************************************************************************************************************/

#include "lm35_sensor.h"
#include "lcd.h"
#include "adc.h"
#include <avr/io.h>
#include "DC_motor.h"
#include "gpio.h"


extern uint8 duty_cycle;   // call the variable in the DC_motor.c file which
// carry the duty_cylcle wanted to be generated by the PWM


/*
 * Description:
 * function that initialize the PWM mode for timer0
 */
void PWM_Timer0_Start(uint8 duty_cycle){  /* send to it the duty cycle required */
	TCNT0 = 0;  // clear the counter register at the beginning
	OCR0 = duty_cycle;  // Setup the compare value based on the required input duty cycle

	// Setup the PWM mode with Non-Inverting
	// Setup the prescaler with F_CPU/8
	TCCR0 =  (1<<WGM00) | (1<<WGM01) | (1<<COM01) | (1<<CS01);

}


int main(void){

	ADC_ConfigType ADC_config= {internal, F_CPU_8}; // configurations we want for the ADC

	uint8 result;      // the value of the temperature
	DC_speed  speedOfMotor = OFF;    // speed of motor
	LCD_init();     // initialize the LCD
	ADC_init(&ADC_config);  // initialize the ADC
	DcMotor_Init(); // initialize the DC motor
	LCD_displayStringRowColumn(0,4,"FAN IS OFF");   // display this statement which will be always displayed
	LCD_moveCursor(1,3); // move the cursor to row 1 and column 3
	LCD_displayString("Temp =    C");  // display this statement which will be always displayed

	while(1){

		result = LM35_getTemperature();   //get the temperature value from the ADC
		LCD_moveCursor(1,10);  // move the cursor to row 1 and column 10
		// display the result on the LCD
		if(result>=100)
		{

			LCD_integerToString(result);

		}
		else
		{
			// if the temperature become less than 100, the third digit will not be cleared,
			// so we want to display empty character to clear that digit
			LCD_integerToString(result);
			LCD_displayCharacter(' ');

		}
		// change the state of the motor and calculate the duty cycle based of the value of the temperature
		if(result >= 120){
			if(speedOfMotor == SPEED_100){

			}
			else
			{
				DcMotor_Rotate(CLOCK_WISE, 100);
				speedOfMotor = SPEED_100;
				PWM_Timer0_Start(duty_cycle);
			}
		}

		else if(result >= 90){
			if(speedOfMotor == SPEED_75){

			}
			else
			{
				DcMotor_Rotate(CLOCK_WISE, 75);
				speedOfMotor = SPEED_75;
				PWM_Timer0_Start(duty_cycle);
			}
		}

		else if(result >= 60){
			if(speedOfMotor == SPEED_50){

			}
			else
			{
				DcMotor_Rotate(CLOCK_WISE, 50);
				speedOfMotor = SPEED_50;
				PWM_Timer0_Start(duty_cycle);
			}
		}
		else if(result >= 30){
			if(speedOfMotor == SPEED_25){

			}
			else
			{
				DcMotor_Rotate(CLOCK_WISE, 25);
				speedOfMotor =SPEED_25;
				PWM_Timer0_Start(duty_cycle);
			}
		}
		else
		{
			DcMotor_Rotate(STOP, 0);
			speedOfMotor =OFF;
			PWM_Timer0_Start(duty_cycle);
		}

		if(speedOfMotor == OFF){
			LCD_moveCursor(0,11); // move the cursor to row 0 and column 11
			LCD_displayString("OFF"); // display the state of the FAN

		}
		else
		{
			LCD_moveCursor(0,11); // move the cursor to row 0 and column 11
			LCD_displayString("ON "); // display the state of the FAN
		}
	}


}
